[project]
name = "probs_with_probs"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
openai = ">=1.30.1,<1.31"
datasets = "==2.17.1"
transformers = "==4.38.1"
matplotlib = ">=3.8.4,<3.9"
jupyter = ">=1.0.0,<1.1"
accelerate = ">=0.30.1,<0.31"
tiktoken = ">=0.6.0,<0.7"
scikit-learn = ">=1.4.2,<1.5"

[pypi-dependencies]
probs_with_probs = { path = ".", editable = true}
